# Generated by Django 2.2.2 on 2019-06-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=10)),
                ('start_date', models.DateField(choices=[('C', 'Conference'), ('S', 'Seminar'), ('P', 'Presentation')], max_length=1)),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('registration', models.BooleanField()),
                ('image', models.CharField(max_length=200)),
                ('ticket_adult', models.IntegerField()),
                ('ticket_child', models.IntegerField()),
            ],
        ),
    ]
