# Generated by Django 2.2.2 on 2019-06-16 21:53

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_auto_20190616_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=200, verbose_name=django.forms.widgets.Textarea),
        ),
    ]
