# Generated by Django 2.2.2 on 2019-06-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_adult',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_child',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=75),
        ),
    ]
