# Generated by Django 2.2.2 on 2019-06-16 22:10

from django.db import migrations, models
import django.forms.widgets
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_auto_20190616_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Description',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name=django.forms.widgets.Textarea),
            preserve_default=False,
        ),
    ]
