# Generated by Django 2.2.2 on 2019-06-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0006_auto_20190616_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='event/%Y/%m/%d'),
        ),
    ]
