# Generated by Django 2.2.2 on 2019-06-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0006_auto_20190613_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.DateField(choices=[('C', 'Conference'), ('S', 'Seminar'), ('P', 'Presentation')], max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(),
        ),
    ]
