# Generated by Django 2.2.2 on 2019-06-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0008_auto_20190616_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='media/nopivture.jpg', upload_to='media/%Y/%m/%d'),
        ),
    ]
