# Generated by Django 2.2.2 on 2019-06-14 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0008_auto_20190614_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventuser',
            name='date',
        ),
    ]
