# Generated by Django 2.2.2 on 2019-06-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0009_remove_eventuser_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
