# Generated by Django 2.2.2 on 2019-06-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0010_eventuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
