# Generated by Django 2.2.2 on 2019-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0012_auto_20190613_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('C', 'Conference'), ('S', 'Seminar'), ('P', 'Presentation')], max_length=1),
        ),
    ]
