# Generated by Django 2.2.2 on 2019-06-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0012_auto_20190616_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='ticket_adult_numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='ticket_child_numbers',
            field=models.IntegerField(default=0),
        ),
    ]
