# Generated by Django 2.2.2 on 2019-06-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0013_auto_20190614_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('C', 'Conference'), ('S', 'Seminar'), ('P', 'Presentation')], default=1, max_length=1),
        ),
    ]
